#!/usr/local/bin/fish
zip -r one.zip index.js node_modules package.json
aws lambda update-function-code --region us-west-2 --profile lambda --function-name slackGoogleImage --zip-file fileb://one.zip
